micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

#datasources:
#  default:
#    url: ${DATASOURCES_DEFAULT_URL}
#    driverClassName: org.postgresql.Driver
#    username: ${DATASOURCES_DEFAULT_USERNAME}
#    password: ${DATASOURCES_DEFAULT_PASSWORD}
#    dialect: POSTGRES
#    schema-generate: create_drop
---
omdb:
  base-url: http://www.omdbapi.com/
  # Create your own apikey here http://www.omdbapi.com/. It's free
  apikey: ${OMDB_API_KEY:xxxxxxxxxxxx}
